//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", ConfigurationName="ServiceReference1.DEHuWsPortType")]
    public interface DEHuWsPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://administracionelectronica.gob.es/notifica/ws/lema/Localiza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DetalleAnexo))]
        System.Threading.Tasks.Task<ServiceReference1.LocalizaResponse> LocalizaAsync(ServiceReference1.LocalizaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://administracionelectronica.gob.es/notifica/ws/lema/PeticionAcceso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DetalleAnexo))]
        System.Threading.Tasks.Task<ServiceReference1.PeticionAccesoResponse> PeticionAccesoAsync(ServiceReference1.PeticionAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://administracionelectronica.gob.es/notifica/ws/lema/ConsultaAnexos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DetalleAnexo))]
        System.Threading.Tasks.Task<ServiceReference1.ConsultaAnexosResponse> ConsultaAnexosAsync(ServiceReference1.ConsultaAnexosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://administracionelectronica.gob.es/notifica/ws/lema/ConsultaAcusePdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DetalleAnexo))]
        System.Threading.Tasks.Task<ServiceReference1.ConsultaAcusePdfResponse> ConsultaAcusePdfAsync(ServiceReference1.ConsultaAcusePdfRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/localiza")]
    public partial class Localiza
    {
        
        private string nifTitularField;
        
        private string nifDestinatarioField;
        
        private string codigoDestinoField;
        
        private System.DateTime fechaDesdeField;
        
        private bool fechaDesdeFieldSpecified;
        
        private System.DateTime fechaHastaField;
        
        private bool fechaHastaFieldSpecified;
        
        private TipoEnvio tipoEnvioField;
        
        private bool tipoEnvioFieldSpecified;
        
        private Opcion[] opcionesLocalizaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nifTitular
        {
            get
            {
                return this.nifTitularField;
            }
            set
            {
                this.nifTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nifDestinatario
        {
            get
            {
                return this.nifDestinatarioField;
            }
            set
            {
                this.nifDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoDestino
        {
            get
            {
                return this.codigoDestinoField;
            }
            set
            {
                this.codigoDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fechaDesde
        {
            get
            {
                return this.fechaDesdeField;
            }
            set
            {
                this.fechaDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDesdeSpecified
        {
            get
            {
                return this.fechaDesdeFieldSpecified;
            }
            set
            {
                this.fechaDesdeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fechaHasta
        {
            get
            {
                return this.fechaHastaField;
            }
            set
            {
                this.fechaHastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHastaSpecified
        {
            get
            {
                return this.fechaHastaFieldSpecified;
            }
            set
            {
                this.fechaHastaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TipoEnvio tipoEnvio
        {
            get
            {
                return this.tipoEnvioField;
            }
            set
            {
                this.tipoEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEnvioSpecified
        {
            get
            {
                return this.tipoEnvioFieldSpecified;
            }
            set
            {
                this.tipoEnvioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion[] opcionesLocaliza
        {
            get
            {
                return this.opcionesLocalizaField;
            }
            set
            {
                this.opcionesLocalizaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/localiza")]
    public enum TipoEnvio
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/localiza")]
    public partial class Opcion
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAcusePdf" +
        "")]
    public partial class Opcion7
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Contenido", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAcusePdf" +
        "")]
    public partial class Contenido2
    {
        
        private string hrefField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAcusePdf" +
        "")]
    public partial class AcusePdf
    {
        
        private string nombreAcuseField;
        
        private Contenido2 contenidoField;
        
        private string mimeTypeField;
        
        private string metadatosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreAcuse
        {
            get
            {
                return this.nombreAcuseField;
            }
            set
            {
                this.nombreAcuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Contenido2 contenido
        {
            get
            {
                return this.contenidoField;
            }
            set
            {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string metadatos
        {
            get
            {
                return this.metadatosField;
            }
            set
            {
                this.metadatosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAcusePdf" +
        "")]
    public partial class RespuestaConsultaAcusePdf
    {
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private AcusePdf acusePdfField;
        
        private Opcion7[] opcionesRespuestaConsultaAcusePdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcionRespuesta
        {
            get
            {
                return this.descripcionRespuestaField;
            }
            set
            {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AcusePdf acusePdf
        {
            get
            {
                return this.acusePdfField;
            }
            set
            {
                this.acusePdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion7[] opcionesRespuestaConsultaAcusePdf
        {
            get
            {
                return this.opcionesRespuestaConsultaAcusePdfField;
            }
            set
            {
                this.opcionesRespuestaConsultaAcusePdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAcusePdf")]
    public partial class Opcion6
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAcusePdf")]
    public partial class IdentificadorAcusePdf
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("csvResguardo", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("referencia", typeof(byte[]), DataType="base64Binary", Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAcusePdf")]
    public partial class ConsultaAcusePdf
    {
        
        private string nifReceptorField;
        
        private string identificadorField;
        
        private string codigoOrigenField;
        
        private IdentificadorAcusePdf identificadorAcusePdfField;
        
        private Opcion6[] opcionesConsultaAcusePdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nifReceptor
        {
            get
            {
                return this.nifReceptorField;
            }
            set
            {
                this.nifReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string codigoOrigen
        {
            get
            {
                return this.codigoOrigenField;
            }
            set
            {
                this.codigoOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public IdentificadorAcusePdf identificadorAcusePdf
        {
            get
            {
                return this.identificadorAcusePdfField;
            }
            set
            {
                this.identificadorAcusePdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion6[] opcionesConsultaAcusePdf
        {
            get
            {
                return this.opcionesConsultaAcusePdfField;
            }
            set
            {
                this.opcionesConsultaAcusePdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAnexos")]
    public partial class Opcion5
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Contenido", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAnexos")]
    public partial class Contenido1
    {
        
        private string hrefField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAnexos")]
    public partial class DocumentoAnexo
    {
        
        private string nombreField;
        
        private Contenido1 contenidoField;
        
        private string mimeTypeField;
        
        private string metadatosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Contenido1 contenido
        {
            get
            {
                return this.contenidoField;
            }
            set
            {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string metadatos
        {
            get
            {
                return this.metadatosField;
            }
            set
            {
                this.metadatosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAnexos")]
    public partial class RespuestaConsultaAnexos
    {
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private DocumentoAnexo documentoField;
        
        private Opcion5[] opcionesRespuestaConsultaAnexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcionRespuesta
        {
            get
            {
                return this.descripcionRespuestaField;
            }
            set
            {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DocumentoAnexo documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion5[] opcionesRespuestaConsultaAnexo
        {
            get
            {
                return this.opcionesRespuestaConsultaAnexoField;
            }
            set
            {
                this.opcionesRespuestaConsultaAnexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAnexos")]
    public partial class Opcion4
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAnexos")]
    public partial class ConsultaAnexos
    {
        
        private string nifReceptorField;
        
        private string identificadorField;
        
        private string codigoOrigenField;
        
        private byte[] referenciaField;
        
        private Opcion4[] opcionesConsultaAnexosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nifReceptor
        {
            get
            {
                return this.nifReceptorField;
            }
            set
            {
                this.nifReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string codigoOrigen
        {
            get
            {
                return this.codigoOrigenField;
            }
            set
            {
                this.codigoOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion4[] opcionesConsultaAnexos
        {
            get
            {
                return this.opcionesConsultaAnexosField;
            }
            set
            {
                this.opcionesConsultaAnexosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class Opcion3
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class AnexosUrl
    {
        
        private AnexoUrl[] anexoUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anexoUrl", Order=0)]
        public AnexoUrl[] anexoUrl
        {
            get
            {
                return this.anexoUrlField;
            }
            set
            {
                this.anexoUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class AnexoUrl : DetalleAnexo
    {
        
        private string enlaceDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string enlaceDocumento
        {
            get
            {
                return this.enlaceDocumentoField;
            }
            set
            {
                this.enlaceDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnexoReferencia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnexoUrl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class DetalleAnexo
    {
        
        private string nombreField;
        
        private string mimeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class AnexoReferencia : DetalleAnexo
    {
        
        private byte[] referenciaDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] referenciaDocumento
        {
            get
            {
                return this.referenciaDocumentoField;
            }
            set
            {
                this.referenciaDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class AnexosReferencia
    {
        
        private AnexoReferencia[] anexoReferenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anexoReferencia", Order=0)]
        public AnexoReferencia[] anexoReferencia
        {
            get
            {
                return this.anexoReferenciaField;
            }
            set
            {
                this.anexoReferenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class Anexos
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anexosReferencia", typeof(AnexosReferencia), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("anexosUrl", typeof(AnexosUrl), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class HashDocumento
    {
        
        private string hashField;
        
        private string algoritmoHashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string algoritmoHash
        {
            get
            {
                return this.algoritmoHashField;
            }
            set
            {
                this.algoritmoHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class Contenido
    {
        
        private string hrefField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class DetalleDocumento
    {
        
        private string nombreField;
        
        private Contenido contenidoField;
        
        private HashDocumento hashDocumentoField;
        
        private string mimeTypeField;
        
        private string metadatosField;
        
        private string enlaceDocumentoField;
        
        private byte[] referenciaDocumentoField;
        
        private byte[] referenciaPdfAcuseField;
        
        private string csvResguardoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Contenido contenido
        {
            get
            {
                return this.contenidoField;
            }
            set
            {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public HashDocumento hashDocumento
        {
            get
            {
                return this.hashDocumentoField;
            }
            set
            {
                this.hashDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string metadatos
        {
            get
            {
                return this.metadatosField;
            }
            set
            {
                this.metadatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string enlaceDocumento
        {
            get
            {
                return this.enlaceDocumentoField;
            }
            set
            {
                this.enlaceDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] referenciaDocumento
        {
            get
            {
                return this.referenciaDocumentoField;
            }
            set
            {
                this.referenciaDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=7)]
        public byte[] referenciaPdfAcuse
        {
            get
            {
                return this.referenciaPdfAcuseField;
            }
            set
            {
                this.referenciaPdfAcuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string csvResguardo
        {
            get
            {
                return this.csvResguardoField;
            }
            set
            {
                this.csvResguardoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso")]
    public partial class RespuestaPeticionAcceso
    {
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string identificadorField;
        
        private string codigoOrigenField;
        
        private System.DateTime fechaEventoField;
        
        private DetalleDocumento documentoField;
        
        private Anexos anexosField;
        
        private Opcion3[] opcionesRespuestaPeticionAccesoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcionRespuesta
        {
            get
            {
                return this.descripcionRespuestaField;
            }
            set
            {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string codigoOrigen
        {
            get
            {
                return this.codigoOrigenField;
            }
            set
            {
                this.codigoOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fechaEvento
        {
            get
            {
                return this.fechaEventoField;
            }
            set
            {
                this.fechaEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DetalleDocumento documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Anexos anexos
        {
            get
            {
                return this.anexosField;
            }
            set
            {
                this.anexosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion3[] opcionesRespuestaPeticionAcceso
        {
            get
            {
                return this.opcionesRespuestaPeticionAccesoField;
            }
            set
            {
                this.opcionesRespuestaPeticionAccesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/peticionAcceso")]
    public partial class Opcion2
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/peticionAcceso")]
    public partial class PeticionAcceso
    {
        
        private string identificadorField;
        
        private string codigoOrigenField;
        
        private string nifReceptorField;
        
        private string nombreReceptorField;
        
        private Evento eventoField;
        
        private string conceptoField;
        
        private Opcion2[] opcionesPeticionAccesoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string codigoOrigen
        {
            get
            {
                return this.codigoOrigenField;
            }
            set
            {
                this.codigoOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nifReceptor
        {
            get
            {
                return this.nifReceptorField;
            }
            set
            {
                this.nifReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nombreReceptor
        {
            get
            {
                return this.nombreReceptorField;
            }
            set
            {
                this.nombreReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Evento evento
        {
            get
            {
                return this.eventoField;
            }
            set
            {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string concepto
        {
            get
            {
                return this.conceptoField;
            }
            set
            {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion2[] opcionesPeticionAcceso
        {
            get
            {
                return this.opcionesPeticionAccesoField;
            }
            set
            {
                this.opcionesPeticionAccesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/peticionAcceso")]
    public enum Evento
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Opcion", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public partial class Opcion1
    {
        
        private string tipoField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public partial class Persona
    {
        
        private string nombreTitularField;
        
        private string nifTitularField;
        
        private string codigoDIR3Field;
        
        private string codigoDIReField;
        
        private string descripcionEntidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreTitular
        {
            get
            {
                return this.nombreTitularField;
            }
            set
            {
                this.nombreTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nifTitular
        {
            get
            {
                return this.nifTitularField;
            }
            set
            {
                this.nifTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoDIR3
        {
            get
            {
                return this.codigoDIR3Field;
            }
            set
            {
                this.codigoDIR3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codigoDIRe
        {
            get
            {
                return this.codigoDIReField;
            }
            set
            {
                this.codigoDIReField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descripcionEntidad
        {
            get
            {
                return this.descripcionEntidadField;
            }
            set
            {
                this.descripcionEntidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public partial class Organismo
    {
        
        private string codigoOrganismoField;
        
        private string nombreOrganismoField;
        
        private string nifOrganismoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoOrganismo
        {
            get
            {
                return this.codigoOrganismoField;
            }
            set
            {
                this.codigoOrganismoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreOrganismo
        {
            get
            {
                return this.nombreOrganismoField;
            }
            set
            {
                this.nombreOrganismoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nifOrganismo
        {
            get
            {
                return this.nifOrganismoField;
            }
            set
            {
                this.nifOrganismoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public partial class Envio
    {
        
        private string identificadorField;
        
        private string codigoOrigenField;
        
        private string conceptoField;
        
        private string descripcionField;
        
        private Organismo organismoEmisorField;
        
        private Organismo organismoEmisorRaizField;
        
        private System.DateTime fechaPuestaDisposicionField;
        
        private TipoEnvio1 tipoEnvioField;
        
        private Vinculo vinculoField;
        
        private Persona titularField;
        
        private string metadatosPublicosField;
        
        private Opcion1[] opcionesEnvioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string codigoOrigen
        {
            get
            {
                return this.codigoOrigenField;
            }
            set
            {
                this.codigoOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string concepto
        {
            get
            {
                return this.conceptoField;
            }
            set
            {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Organismo organismoEmisor
        {
            get
            {
                return this.organismoEmisorField;
            }
            set
            {
                this.organismoEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Organismo organismoEmisorRaiz
        {
            get
            {
                return this.organismoEmisorRaizField;
            }
            set
            {
                this.organismoEmisorRaizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime fechaPuestaDisposicion
        {
            get
            {
                return this.fechaPuestaDisposicionField;
            }
            set
            {
                this.fechaPuestaDisposicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TipoEnvio1 tipoEnvio
        {
            get
            {
                return this.tipoEnvioField;
            }
            set
            {
                this.tipoEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Vinculo vinculo
        {
            get
            {
                return this.vinculoField;
            }
            set
            {
                this.vinculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Persona titular
        {
            get
            {
                return this.titularField;
            }
            set
            {
                this.titularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string metadatosPublicos
        {
            get
            {
                return this.metadatosPublicosField;
            }
            set
            {
                this.metadatosPublicosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion1[] opcionesEnvio
        {
            get
            {
                return this.opcionesEnvioField;
            }
            set
            {
                this.opcionesEnvioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TipoEnvio", Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public enum TipoEnvio1
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public enum Vinculo
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza")]
    public partial class RespuestaLocaliza
    {
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string nifPeticionField;
        
        private Envio[] enviosField;
        
        private bool hayMasResultadosField;
        
        private Opcion1[] opcionesRespuestaLocalizaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcionRespuesta
        {
            get
            {
                return this.descripcionRespuestaField;
            }
            set
            {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nifPeticion
        {
            get
            {
                return this.nifPeticionField;
            }
            set
            {
                this.nifPeticionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Envio[] envios
        {
            get
            {
                return this.enviosField;
            }
            set
            {
                this.enviosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool hayMasResultados
        {
            get
            {
                return this.hayMasResultadosField;
            }
            set
            {
                this.hayMasResultadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opcion", IsNullable=false)]
        public Opcion1[] opcionesRespuestaLocaliza
        {
            get
            {
                return this.opcionesRespuestaLocalizaField;
            }
            set
            {
                this.opcionesRespuestaLocalizaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LocalizaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/localiza", Order=0)]
        public ServiceReference1.Localiza Localiza;
        
        public LocalizaRequest()
        {
        }
        
        public LocalizaRequest(ServiceReference1.Localiza Localiza)
        {
            this.Localiza = Localiza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LocalizaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza", Order=0)]
        public ServiceReference1.RespuestaLocaliza RespuestaLocaliza;
        
        public LocalizaResponse()
        {
        }
        
        public LocalizaResponse(ServiceReference1.RespuestaLocaliza RespuestaLocaliza)
        {
            this.RespuestaLocaliza = RespuestaLocaliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeticionAccesoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/peticionAcceso", Order=0)]
        public ServiceReference1.PeticionAcceso PeticionAcceso;
        
        public PeticionAccesoRequest()
        {
        }
        
        public PeticionAccesoRequest(ServiceReference1.PeticionAcceso PeticionAcceso)
        {
            this.PeticionAcceso = PeticionAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeticionAccesoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso", Order=0)]
        public ServiceReference1.RespuestaPeticionAcceso RespuestaPeticionAcceso;
        
        public PeticionAccesoResponse()
        {
        }
        
        public PeticionAccesoResponse(ServiceReference1.RespuestaPeticionAcceso RespuestaPeticionAcceso)
        {
            this.RespuestaPeticionAcceso = RespuestaPeticionAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaAnexosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAnexos", Order=0)]
        public ServiceReference1.ConsultaAnexos ConsultaAnexos;
        
        public ConsultaAnexosRequest()
        {
        }
        
        public ConsultaAnexosRequest(ServiceReference1.ConsultaAnexos ConsultaAnexos)
        {
            this.ConsultaAnexos = ConsultaAnexos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaAnexosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAnexos", Order=0)]
        public ServiceReference1.RespuestaConsultaAnexos RespuestaConsultaAnexos;
        
        public ConsultaAnexosResponse()
        {
        }
        
        public ConsultaAnexosResponse(ServiceReference1.RespuestaConsultaAnexos RespuestaConsultaAnexos)
        {
            this.RespuestaConsultaAnexos = RespuestaConsultaAnexos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaAcusePdfRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/consultaAcusePdf", Order=0)]
        public ServiceReference1.ConsultaAcusePdf ConsultaAcusePdf;
        
        public ConsultaAcusePdfRequest()
        {
        }
        
        public ConsultaAcusePdfRequest(ServiceReference1.ConsultaAcusePdf ConsultaAcusePdf)
        {
            this.ConsultaAcusePdf = ConsultaAcusePdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaAcusePdfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAcusePdf" +
            "", Order=0)]
        public ServiceReference1.RespuestaConsultaAcusePdf RespuestaConsultaAcusePdf;
        
        public ConsultaAcusePdfResponse()
        {
        }
        
        public ConsultaAcusePdfResponse(ServiceReference1.RespuestaConsultaAcusePdf RespuestaConsultaAcusePdf)
        {
            this.RespuestaConsultaAcusePdf = RespuestaConsultaAcusePdf;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DEHuWsPortTypeChannel : ServiceReference1.DEHuWsPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DEHuWsPortTypeClient : System.ServiceModel.ClientBase<ServiceReference1.DEHuWsPortType>, ServiceReference1.DEHuWsPortType
    {
        
        public DEHuWsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.LocalizaResponse> ServiceReference1.DEHuWsPortType.LocalizaAsync(ServiceReference1.LocalizaRequest request)
        {
            return base.Channel.LocalizaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LocalizaResponse> LocalizaAsync(ServiceReference1.Localiza Localiza)
        {
            ServiceReference1.LocalizaRequest inValue = new ServiceReference1.LocalizaRequest();
            inValue.Localiza = Localiza;
            return ((ServiceReference1.DEHuWsPortType)(this)).LocalizaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.PeticionAccesoResponse> ServiceReference1.DEHuWsPortType.PeticionAccesoAsync(ServiceReference1.PeticionAccesoRequest request)
        {
            return base.Channel.PeticionAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PeticionAccesoResponse> PeticionAccesoAsync(ServiceReference1.PeticionAcceso PeticionAcceso)
        {
            ServiceReference1.PeticionAccesoRequest inValue = new ServiceReference1.PeticionAccesoRequest();
            inValue.PeticionAcceso = PeticionAcceso;
            return ((ServiceReference1.DEHuWsPortType)(this)).PeticionAccesoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ConsultaAnexosResponse> ServiceReference1.DEHuWsPortType.ConsultaAnexosAsync(ServiceReference1.ConsultaAnexosRequest request)
        {
            return base.Channel.ConsultaAnexosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ConsultaAnexosResponse> ConsultaAnexosAsync(ServiceReference1.ConsultaAnexos ConsultaAnexos)
        {
            ServiceReference1.ConsultaAnexosRequest inValue = new ServiceReference1.ConsultaAnexosRequest();
            inValue.ConsultaAnexos = ConsultaAnexos;
            return ((ServiceReference1.DEHuWsPortType)(this)).ConsultaAnexosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ConsultaAcusePdfResponse> ServiceReference1.DEHuWsPortType.ConsultaAcusePdfAsync(ServiceReference1.ConsultaAcusePdfRequest request)
        {
            return base.Channel.ConsultaAcusePdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ConsultaAcusePdfResponse> ConsultaAcusePdfAsync(ServiceReference1.ConsultaAcusePdf ConsultaAcusePdf)
        {
            ServiceReference1.ConsultaAcusePdfRequest inValue = new ServiceReference1.ConsultaAcusePdfRequest();
            inValue.ConsultaAcusePdf = ConsultaAcusePdf;
            return ((ServiceReference1.DEHuWsPortType)(this)).ConsultaAcusePdfAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
